version: '3'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_PASSWORD=bug"
      - "POSTGRES_DB=bug"
    volumes:
      - postgres-bug:/var/lib/postgresql/data
    command: [ 'postgres', '-c', 'log_statement=all' ]

volumes:
  postgres-bug:

